language: node_js
node_js: stable

# S: Build Lifecycle
install:
  #- npm rebuild node-sass --force
  - npm install
  #- npm install hexo-renderer-sass --save 
  #- npm install hexo-renderer-scss --save
  #- npm install hexo-generator-json-content --save
  - npm install hexo-renderer-jade@0.3.0 --save
  - npm install hexo-renderer-stylus --save

before_script:
  - chmod -R 777 ./node_modules
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "reallinxu"
  - git config user.email "1003514534@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/reallinxu/reallinxu.github.io.git
