# Header
menu:
  主页: /
  留言板: /MBoard

# Content
excerpt_link: 更多内容
prev: 上一页
next: 下一页
reply: 评论
share: 分享
fancybox: true

# Sidebar
widgets:
- about
- category
#- support
- music
- archive
- recent_posts
- tagcloud
- link
#- ad
#- account

# Miscellaneous
google_analytics:
duoshuo_shortname: iwbo
rss: 
favicon: 
google_site_verification: 
baidu_site_verification: 
bing_site_verification: 
music: http://7xsg2l.com1.z0.glb.clouddn.com/Goose%20House%20-%20%E5%85%89%E3%82%8B%E3%81%AA%E3%82%89.mp3